# Site settings
title: Daintya
email: out_1018@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://daintya.com" # the base hostname & protocol for your site
twitter_username: daintya
github_username:  Com-Mean
encoding: utf-8
# Build settings
markdown: kramdown